apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aether-controller
rules:
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
