name: Deployment

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --tag aether:latest

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$(echo "ghcr.io/${{ github.repository_owner }}/aether" | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.sha }}" | cut -c1-7)

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag aether:latest $IMAGE_ID:latest
          docker tag aether:latest $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION
